### ISSUE TITLE
Шейдер-граф, эффект ветра

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/design-practice#14]
Необходимо создать тематический спрайт, пусть это будет картонный стакан с трубочкой, к которому необходимо применить эффект, который продемонстрировать на [видеоуроке](https://www.youtube.com/watch?v=VcUiksxYT88&list=PLzDRvYVwl53tpvp6CP6e-Mrl6dmxs9uhx&index=5).

**Comment by LadygaPavel** [comment]
https://github.com/PAD1K/design-practice/assets/83593908/c0255c95-395d-4eb3-b791-d5fcf69ab44e
