### ISSUE TITLE
Шейдер-граф, эффект строительства

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/design-practice#15]
Необходимо реализовать тематический спрайт, пусть это будет пряничный дом, к которому необходимо применить эффект, который продемонстрирован на [видеоуроке](https://www.youtube.com/watch?v=OzyLWXTr3Io&list=PLzDRvYVwl53tpvp6CP6e-Mrl6dmxs9uhx&index=6).

**Comment by LadygaPavel** [comment]
Очень проблематичный инструмент из-за изменений в новых версиях, постоянно надо разбираться с альфа-каналом и искать решения больших проблем
