### ISSUE TITLE
Модификация визуала

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/design-practice#6]
Необходимо отказаться от текущего вида рук персонажа и изменить их на круги. Схематическое изображение прикрепляю.

![Image](https://github.com/PAD1K/design-practice/assets/82671681/e309083c-a9e7-4f25-b8ef-089d872cf188)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/design-practice/assets/83593908/f2b56ef9-f038-4161-992e-fc18429348c5)
