### ISSUE TITLE
Добавление Particle System

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/design-practice#7]
Необходимо реализовать эффект передвижения пончика по земле с помощью Particle System, за основу можно взять следующий [видеоурок](https://www.youtube.com/watch?v=oPUxv-zClNA&t=120s). Для дополнительной информации есть альтернативные источникик;[ №1](https://www.youtube.com/watch?v=FEA1wTMJAR0), [№2](https://www.youtube.com/watch?v=_z68_OoC_0o&t=231s).

**Comment by LadygaPavel** [comment]
Анимация, партиклы сделаны, проверены, осталось перенести в свой проект
